################################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

[package]
author = "Eclipse Foundation uProtocol project"
documentation = "https://github.com/eclipse-uprotocol/up-spec#readme"
edition = "2021"
exclude = [
    "tests/*",
    "tools/*",
    ".devcontainer/*",
    ".vscode/*",
    ".github/*",
    ".gitignore",
]
keywords = ["uProtocol", "SDK"]
license = "Apache-2.0"
name = "up-client-mqtt5-rust"
readme = "README.md"
repository = "https://github.com/eclipse-uprotocol/up-client-mqtt5-rust"
rust-version = "1.72"
version = "0.1.0"

[dependencies]
async-trait = { version = "0.1" }
bytes = { version = "1.5" }
chrono = { version = "0.4" }
cloudevents-sdk = { version = "0.7" }
mediatype = "0.19"
paho-mqtt = { version = "0.12.1" }
protobuf = { version = "3.3" }
rand = { version = "0.8" }
regex = { version = "1.10" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
url = { version = "2.5" }
uuid = { version = "1.7", features = ["v8"] }

[build-dependencies]
protobuf-codegen = { version = "3.3" }
protoc-bin-vendored = { version = "3.0" }
ureq = { version = "2.9.1", features = ["proxy-from-env"] }

[dev-dependencies]
test-case = { version = "3.3" }